Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : junção de nome e sobrenome
// Autor(a)    : gabriel
// Data atual  : 07/08/2020
Var
nome: caracter
sobrenome: caracter


Inicio
 escreva ("nome:")
 leia (nome)
 
 escreva ("sobrenome:")
 leia  (sobrenome)

 escreval()
 
 
 escreva (nome," ",sobrenome)




Fimalgoritmo